### ISSUE TITLE
issue in step 3 / ubuntu 18.04

### ISSUE THREAD

**Issue by Synaxis** [Awkan/DockerSF#4]
Hi , i'm having this bug (very weird)
thanks for the work on the repo i hope it will work
```
Documents/mysql/DockerSF# docker-compose build
db uses an image, skipping
Building php-fpm
Step 1/13 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
6b98dfc16071: Pull complete
4001a1209541: Pull complete
6319fc68c576: Pull complete
b24603670dc3: Pull complete
97f170c87c6f: Pull complete
Digest: sha256:5f4bdc3467537cbbe563e80db2c3ec95d548a9145d64453b06939c4592d67b6d
Status: Downloaded newer image for ubuntu:16.04
 ---> 113a43faa138
Step 2/13 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 4353dc2e64dc
Removing intermediate container 4353dc2e64dc
 ---> d116980e80ec
Step 3/13 : RUN apt-get update && apt-get -y upgrade && apt-get install -y software-properties-common
 ---> Running in 63d8670660bc
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
```

**Comment by Awkan** [comment]
Hi,

Thanks for using this Docker configuration.

I've investigate in your problem but I can't reproduce it ... Could you provide more explanations ?

Your error seems to be a DNS issue. Can you successfully ping `security.ubuntu.com` or `archive.ubuntu.com` ?

**Comment by Synaxis** [comment]
Yes ,

**Comment by Synaxis** [comment]
Yes ,syn@synaxis:~$ ping security.ubuntu.com
PING security.ubuntu.com(keeton.canonical.com (2001:67c:1560:8001::14)) 56 data bytes
64 bytes from keeton.canonical.com (2001:67c:1560:8001::14): icmp_seq=1 ttl=47 time=202 ms
64 bytes from keeton.canonical.com (2001:67c:1560:8001::14): icmp_seq=2 ttl=47 time=203 ms
--- security.ubuntu.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 202.568/203.090/203.913/0.694 ms
syn@synaxis:~$ ping  archive.ubuntu.com
PING archive.ubuntu.com(yukinko.canonical.com (2001:67c:1360:8001::21)) 56 data bytes
64 bytes from yukinko.canonical.com (2001:67c:1360:8001::21): icmp_seq=1 ttl=53 time=189 ms
^C
1 packets transmitted, 1 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 189.209/189.215/189.221/0.006 ms

Wow 200 MS , hold on i think there's something wrong in my config, i'll reply it asap
thanks

**Comment by Synaxis** [comment]
@Awkan I'm using mirrors from security.ubuntu.com && archive.ubuntu.com 
Now it's fine , thank you for your time!
